---
title: "CodeBook"
author: "jc"
date: "May 15, 2016"
output: html_document
---



# Raw data collection

Raw data are obtained from UCI Machine Learning repository. In particular we used
the *Human Activity Recognition Using Smartphones Data Set* [[1](#uci-har)],
that was used by the original collectors to conduct experiments exploiting
Support Vector Machine (SVM) [[2](#har-smart)].

Activity Recognition (AR) aims to recognize the actions and goals of one or more agents
from a series of observations on the agents' actions and the environmental conditions
[[3](#activity-recognition)]. The collectors used a sensor based approach employing
smartphones as sensing tools. Smartphones are an effective solution for AR, because
they come with embedded built-in sensors such as microphones, dual cameras, accelerometers,
gyroscopes, etc.


The data was obtained by experiments carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities *(WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING*) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually [[4](#har-smart2)]. 

The obtained data set has been randomly partitioned into two sets, where 70% of
the volunteers was selected for generating the *training* data and 30% the *test* data.

--------------------------------------------------------------------------------------------

The [data](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) is located in a folder labeled 'UCI HAR Dataset'.

We will not use all of the data in the above file. For the purposes of this project the relevant data is best understood if organized according the following scheme. 

1. SUBJECT FILES
  + test/subject_test.txt
  + train/subject_train.txt
2. DATA FILES AND LABELS
  + test/X_test.txt
  + train/X_train.txt
  + features.txt - Names of (column) variables 
3. ACTIVITY FILES AND LABELS
  + test/y_test.txt
  + train/y_train.txt
  + activity_labels.txt - The names of the 6 different activities.

The subjects of the experiment are broken into two groups: train and test. Then experiments are performed. The results of each experiment can be thought of as a vector with 563 components : (subject, activity, features).

Subject is one of the 30 subjects numbered 1-30 (subject_ test, subject_ train). The activity is one of the six activitus *(WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING*) (y_ test, y_ train, activity_ labels) and then a 561 element feature vector which contains items likes 'fBodyBodyGyroMag-min()'. These are the variables that were measured ( feature.txt file and X_ train /X_test).



__________________________________________________________________________________________________

# Instructions for assignment

You should create one R script called __run_analysis.R__ that does the following.

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Uses descriptive activity names to name the activities in the data set
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable   for each activity and each subject.





 The Code book describes the variables, the data, and any transformations or work that you performed to clean up the data.


### 1. Merges the training and the test sets to create one data set.

Test and training data (X_ train.txt, X_ test.txt), subject ids (subject_train.txt,
subject_ test.txt) and activity ids (y_ train.txt, y_test.txt) are merged to obtain
a single data set. Variables are labelled with the names assigned by original
collectors (features.txt).

### 2. Extracts only the measurements on the mean and standard deviation for each measurement.

From the merged data set is extracted an intermediate data set, __I__, with only the
values of estimated mean (variables/features with labels that contain "mean") and standard
deviation (variables/features with labels that contain "std").

### 3. Uses descriptive activity names to name the activities in the data set

A new column is added to the intermediate data set, __I__, with the activity description.
ActivityId column is used to look up descriptions in activity_labels.txt.

### 4. Uses descriptive activity names to name the activities in the data set

Labels given from the original collectors  i.e. activity.txt, y_train, y_test and features were changed
 to obtain valid R names without parentheses, dashes and commas and to obtain more descriptive labels

The following is a partial explicit rendering of the casting of the raw names into more descriptive names.

Name                                  |  Domain (Time or Frequency)                | 
| ----------------------------------- |:------------------------------------------:| 
|tBodyAcc-mean()-X                    | TimeDomain.BodyAcceleration.Mean.X         | 
|fBodyAcc-mean()-X                    | FrequencyDomain.BodyAcceleration.Mean.X    |      
|tGravityAcc-mean()-Y                 | TimeDomain.GravityAcceleration.Y           |
|fGravityAcc-mean()-Y                 | FrequencyDomain.GravityAcceleration.Y      |
|tBodyAccJerk-mean()-Z                | TimeDomain.BodyAccelerationJerk.Z          |
|fBodyAccJerk-mean()-Z                | FrequencyDomain.BodyAccelerationJerk.Z     |
| ...                                 |          ...                               |  




### 5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable   for each activity and each subject.

From the intermediate data set is created a final tidy data set where numeric
variables are averaged for each (__Subject__, __Activity__) pair.

The tidy data set contains in ['wide format'](http://seananderson.ca/2013/10/19/reshape.html) the following long format data of 10299 observations with 81 variables organized as follows:

*  __Subject__: 1, 3, 5,...
*   __Activity__: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
*  a 79-feature vector with time and frequency domain signal variables (numeric)

The data set is written to the file mean_by_act_sub.txt.




References
----------

1.  <a name="uci-har"/>Human Activity Recognition Using Smartphones Data Set.
    URL: <http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>. Accessed 05/21/2014
2. <a name="har-smart"/>Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz.
   *Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine*.
   International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012
3.  <a name="activity-recognition"/>Activity recognition. URL: <http://en.wikipedia.org/wiki/Activity_recognition>.
    Accessed 05/21/2014
4. <a name="har-smart2"/>Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz.
   *A Public Domain Dataset for Human Activity Recognition Using Smartphones*.
   ESANN 2013 proceedings, European Symposium on Artificial Neural Networks, Computational Intelligence and
   Machine Learning. Bruges (Belgium), 24-26 April 2013




